
cc_library(
    name = "skphxqueue",
    srcs = [
    ],
    hdrs = [
    ],
    includes = ['.'],
    deps = [
    ],
    copts = [
        "-std=c++11",
    ],
    linkopts = [
    ],
    visibility = ["//visibility:public"],
)

