
cc_library(
    name = "utils",
    srcs = [
        "callgraph_util.cpp",
    ],
    hdrs = [
    ],
    includes = ['.'],
    deps = [
        "//phxqueue:include",
        "//comm2/core:core",
        "//comm2/svrkit:svrkit_cm",
        "//comm2/svrkit:svrkitepoll",
    ],
    copts = [
        "-std=c++11",
    ],
    linkopts = [
    ],
    visibility = ["//visibility:public"],
)

